version: "3.2"
services:
  logana01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    container_name: logana01
    environment:
      - node.name=logana01
      - discovery.seed_hosts=logana01
      - cluster.initial_master_nodes=logana01
      - cluster.name=logana-es
      - bootstrap.memory_lock=true
      - http.port=9220-9300
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - type: bind
        source: ./elasticsearch/plugins
        target: /usr/share/elasticsearch/plugins
#      - type: bind
#        source: ./elasticsearch/data01
      - type: volume
        source: esdata01
        target: /usr/share/elasticsearch/data
        volume:
          nocopy: true
    ports:
      - target: 9220
        published: 9220
        protocol: tcp
        mode: host
    networks:
      - esnet
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

volumes:
  esdata01:
    driver: local

networks:
  esnet:
    driver: bridge
