version: "3.2"
services:
  logana02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: logana02
    environment:
      - node.name=logana02
      - discovery.seed_hosts=logana01
      - cluster.initial_master_nodes=logana01
      - cluster.name=logana-es
      - bootstrap.memory_lock=true
			- http.port=9220-9300
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - type: bind
        source: ./elasticsearch/plugins
        target: /usr/share/elasticsearch/plugins
#      - type: bind
#        source: ./elasticsearch/data02
      - type: volume
        source: esdata02
        target: /usr/share/elasticsearch/data
        volume:
          nocopy: true
    ports:
      - target: 9220
        published: 9221
        protocol: tcp
        mode: host
    networks:
      - esnet
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    depends_on:
      - logana01

volumes:
  esdata02:
    driver: local

